# Generated by Django 2.1.4 on 2018-12-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('grupo', models.CharField(choices=[('Escola', 'Prédio')], max_length=15, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caixa', models.CharField(max_length=4, verbose_name='Número da ccaixa')),
                ('cor', models.CharField(max_length=15, verbose_name='Cor')),
                ('etiqueta', models.CharField(max_length=20, verbose_name='Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cod_colecao', models.CharField(max_length=6, verbose_name='Número da coleção')),
            ],
            options={
                'verbose_name_plural': 'coleções',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data do empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data da devolução')),
                ('devolvido', models.BooleanField()),
                ('amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Amigo')),
            ],
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edicao', models.CharField(max_length=10, verbose_name='Edição')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Caixa')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Colecao')),
            ],
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Revista'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='colecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Colecao'),
        ),
    ]
