# Generated by Django 2.1.4 on 2018-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='grupo',
            field=models.CharField(choices=[('Escola', 'Escola'), ('Prédio', 'Prédio')], max_length=15, verbose_name='Grupo'),
        ),
    ]
