# Generated by Django 2.1.4 on 2018-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_auto_20181221_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='numero_caixa',
            field=models.CharField(max_length=4, verbose_name='Número da caixa'),
        ),
    ]
